name: Greetings

on: [pull_request, issues]

jobs:
  greeting:Hello everyone it's nice to meet you this is my first project hoping to make an Android app of some type!!Any suggestions lmk I'm a newbie!😂
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Message that will be displayed on users'' first issue'
        pr-message: 'Message that will be displayed on users'' first pr'
